### ISSUE TITLE
Problem getting it to work as a custom role

### ISSUE THREAD

**Issue by raj45** [zenoamaro/ansible-postgresql#6] opened 2015-06-29 13:32 UTC
I added the PostgreSQL Ansible script to another Ansible project called [Vlad](https://github.com/hashbangcode/vlad) as a custom role, and it seems to get quite far on the default settings provided with the role.

**How to replicate, and the outcome below:**
<pre>mkdir vlad_postgres
cd vlad_postgres/
git clone https://github.com/hashbangcode/vlad.git
git clone https://github.com/zenoamaro/ansible-postgresql.git
mv ansible-postgresql/ vlad_custom
cp vlad/vlad/example.settings.yml vlad/vlad/settings.yml
vi vlad/vlad/settings.yml # change boxname to "boxname: vladtest" and add "custom_provision: true"
cd vlad
vagrant up
vagrant ssh</pre>

**Result**
<pre>TASK: [vlad_custom | Adding APT repository key] ******************************* 
changed: [192.168.100.100]

TASK: [vlad_custom | Add PostgreSQL official APT repository] ****************** 
changed: [192.168.100.100]

TASK: [vlad_custom | Install PostgreSQL] ************************************** 
changed: [192.168.100.100]

TASK: [vlad_custom | Install dependencies for the Ansible module] ************* 
changed: [192.168.100.100] => (item=python-psycopg2)

TASK: [vlad_custom | Install development headers] ***************************** 
skipping: [192.168.100.100]

TASK: [vlad_custom | Install PostgreSQL contribs] ***************************** 
skipping: [192.168.100.100]

TASK: [vlad_custom | Add postgis extensions] ********************************** 
skipping: [192.168.100.100]

TASK: [vlad_custom | Create the necessary directories] ************************ 
changed: [192.168.100.100] => (item=/etc/postgresql/9.4/main)
changed: [192.168.100.100] => (item=/var/lib/postgresql/9.4/main)
ok: [192.168.100.100] => (item=/var/run/postgresql)
changed: [192.168.100.100] => (item=/var/log/postgresql)

TASK: [vlad_custom | Configure PostgreSQL] ************************************ 
changed: [192.168.100.100] => (item=postgresql.conf)
changed: [192.168.100.100] => (item=pg_ctl.conf)
changed: [192.168.100.100] => (item=environment)

TASK: [vlad_custom | Configure PostgreSQL (authentication)] ******************* 
changed: [192.168.100.100]

TASK: [vlad_custom | Configure PostgreSQL (ident)] **************************** 
changed: [192.168.100.100]

NOTIFIED: [vlad_custom | restart postgresql] ********************************** 
failed: [192.168.100.100] => {"failed": true}
msg:  * Stopping PostgreSQL 9.4 database server
   ...done.
 * Starting PostgreSQL 9.4 database server
 * Error: could not exec /usr/lib/postgresql/9.4/bin/pg_ctl /usr/lib/postgresql/9.4/bin/pg_ctl start -D /var/lib/postgresql/9.4/main -l /var/log/postgresql/postgresql-9.4-main.log -s -o  -c config_file="/etc/postgresql/9.4/main/postgresql.conf" : 
   ...fail!

FATAL: all hosts have already failed -- aborting

NOTIFIED: [vlad_custom | restart postgresql] ********************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting

FATAL: all hosts have already failed -- aborting

NOTIFIED: [vlad_custom | restart postgresql] ********************************** 
FATAL: no hosts matched or all hosts have already failed -- aborting

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/raj/site_custom.retry

192.168.100.100            : ok=9    changed=8    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.</pre>

Can anyone see if I need to change something in one or the other code?

**Comment by zenoamaro** [comment] 2015-06-29 15:47
Hi, thanks for reporting this. I think this is a duplicate of #5.

**Closed by zenoamaro** 2015-06-29 15:47 UTC
